export const START_LOAD_INITIAL_LIST="LOAD_INITIAL_LIST"
export const FINISH_LOAD_INITIAL_LIST="FINISH_LOAD_INITIAL_LIST"

export const START_LOAD_FILTERED_LIST="START_LOAD_FILTERED_LIST"
export const FINISH_LOAD_FILTERED_LIST="FINISH_LOAD_FILTERED_LIST"

export const START_PROCESSING="START_PROCESSING"
export const STOP_PROCESSING="STOP_PROCESSING"

export const CHANGE_FIND_TEXT="CHANGE_FIND_TEXT" 